---
- name: Copy nginx configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    mode: '0644'
  loop:
    - coffee
    - influxdb2
    - lhartung
    - vikunja
    - wordpress

- name: Remove the default site file
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable service nginx
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    masked: no
    state: restarted
