version: "2.4"

services:
  prometheus:
    image: prom/prometheus
    mem_limit: 200m
    mem_reservation: 100m
    ports:
      - "127.0.0.1:9090:9090"
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana
    mem_limit: 200m
    mem_reservation: 100m
    environment:
      GF_SERVER_ROOT_URL: https://coffee.lhartung.com/grafana
      GF_SECURITY_ADMIN_PASSWORD: fluffykitty
    ports:
      - "127.0.0.1:9030:3000"
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
  prometheus-data:
