version: "3.3"

services:
  homemealplan:
    build: mealplanner
    image: homemealplan

    mem_limit: 200m
    mem_reservation: 100m

    ports:
      - "127.0.0.1:3000:3000"

    restart: always

    volumes:
      - ./mealplanner/mealplanner.db:/app/mealplanner.db

  myfreezer:
    build: myfreezer-backend
    image: myfreezer

    mem_limit: 200m
    mem_reservation: 100m

    ports:
      - "127.0.0.1:6000:6000"

    restart: always

    volumes:
      - ./myfreezer-backend/classifier.json:/usr/src/app/classifier.json
      - ./myfreezer-backend/classifier.onnx:/usr/src/app/classifier.onnx
      - ./myfreezer-backend/myfreezer.db:/usr/src/app/myfreezer.db

  db:
    image: mariadb
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: tah9eeCoomoy5eim
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: queib0Yiiy6eivie
      MARIADB_DATABASE: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./volumes/wordpress:/var/www/html
      - ./wordpress/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress/php.ini-production:/usr/local/etc/php/php.ini-production
#      - ./docker-php-ext-gd.ini:/usr/local/etc/php/conf.d/docker-php-ext-gd.ini
#      - ./docker-php-ext-imagick.ini:/usr/local/etc/php/conf.d/docker-php-ext-imagick.ini
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: queib0Yiiy6eivie
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: "true"

  taskd:
    image: ghcr.io/connectical/taskd
    volumes:
      - ./volumes/taskd:/var/taskd
    environment:
      CERT_BITS: 4096
      CERT_EXPIRATION_DAYS: 365
      CERT_ORGANIZATION: LanceNet
      CERT_CN: coffee2.lhartung.com
      CERT_COUNTRY: US
      CERT_STATE: Wisconsin
      CERT_LOCALITY: Madison
    ports:
      - "53589:53589"

  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - ./volumes/influxdb2-data:/var/lib/influxdb2
      - ./volumes/influxdb2-config:/etc/influxdb2

secrets:
  influxdb2-admin-username:
    file: .env.influxdb2-admin-username
  influxdb2-admin-password:
    file: .env.influxdb2-admin-password
  influxdb2-admin-token:
    file: .env.influxdb2-admin-token
